{"category":"APP","errors":[{"attributes":{"genre":"TECHNICAL","http_status":500,"reason":"Error: Cannot set headers after they are sent to the client\n    at ServerResponse.setHeader (node:_http_outgoing:655:11)\n    at ServerResponse.header (/opt/opencti/build/node_modules/express/lib/response.js:794:10)\n    at ServerResponse.send (/opt/opencti/build/node_modules/express/lib/response.js:174:12)\n    at ServerResponse.json (/opt/opencti/build/node_modules/express/lib/response.js:278:15)\n    at ServerResponse.send (/opt/opencti/build/node_modules/express/lib/response.js:162:21)\n    at /opt/opencti/build/src/http/httpPlatform.js:490:21\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"},"message":"Engine unhandled rejection","name":"UNKNOWN_ERROR","stack":"GraphQLError: Engine unhandled rejection\n    at error (/opt/opencti/build/src/config/errors.js:7:10)\n    at UnknownError (/opt/opencti/build/src/config/errors.js:81:47)\n    at process.<anonymous> (/opt/opencti/build/src/boot.js:61:16)\n    at process.emit (node:events:519:28)\n    at process.emit (/opt/opencti/build/node_modules/source-map-support/source-map-support.js:516:21)\n    at emitUnhandledRejection (node:internal/process/promises:250:13)\n    at throwUnhandledRejectionsMode (node:internal/process/promises:385:19)\n    at processPromiseRejections (node:internal/process/promises:470:17)\n    at processTicksAndRejections (node:internal/process/task_queues:96:32)"}],"level":"error","message":"Engine unhandled rejection","source":"backend","timestamp":"2024-11-25T13:16:26.656Z","version":"6.4.0"}
{"category":"APP","errors":[{"attributes":{"genre":"TECHNICAL","http_status":500,"reason":"Error: Cannot set headers after they are sent to the client\n    at ServerResponse.setHeader (node:_http_outgoing:655:11)\n    at ServerResponse.header (/opt/opencti/build/node_modules/express/lib/response.js:794:10)\n    at ServerResponse.send (/opt/opencti/build/node_modules/express/lib/response.js:174:12)\n    at ServerResponse.json (/opt/opencti/build/node_modules/express/lib/response.js:278:15)\n    at ServerResponse.send (/opt/opencti/build/node_modules/express/lib/response.js:162:21)\n    at /opt/opencti/build/src/http/httpPlatform.js:490:21\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"},"message":"Engine unhandled rejection","name":"UNKNOWN_ERROR","stack":"GraphQLError: Engine unhandled rejection\n    at error (/opt/opencti/build/src/config/errors.js:7:10)\n    at UnknownError (/opt/opencti/build/src/config/errors.js:81:47)\n    at process.<anonymous> (/opt/opencti/build/src/boot.js:61:16)\n    at process.emit (node:events:519:28)\n    at process.emit (/opt/opencti/build/node_modules/source-map-support/source-map-support.js:516:21)\n    at emitUnhandledRejection (node:internal/process/promises:250:13)\n    at throwUnhandledRejectionsMode (node:internal/process/promises:385:19)\n    at processPromiseRejections (node:internal/process/promises:470:17)\n    at processTicksAndRejections (node:internal/process/task_queues:96:32)"}],"level":"error","message":"Engine unhandled rejection","source":"backend","timestamp":"2024-11-25T13:16:39.356Z","version":"6.4.0"}
{"category":"APP","errors":[{"attributes":{"genre":"TECHNICAL","http_status":500,"reason":"Error: Cannot set headers after they are sent to the client\n    at ServerResponse.setHeader (node:_http_outgoing:655:11)\n    at ServerResponse.header (/opt/opencti/build/node_modules/express/lib/response.js:794:10)\n    at ServerResponse.send (/opt/opencti/build/node_modules/express/lib/response.js:174:12)\n    at ServerResponse.json (/opt/opencti/build/node_modules/express/lib/response.js:278:15)\n    at ServerResponse.send (/opt/opencti/build/node_modules/express/lib/response.js:162:21)\n    at /opt/opencti/build/src/http/httpPlatform.js:490:21\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"},"message":"Engine unhandled rejection","name":"UNKNOWN_ERROR","stack":"GraphQLError: Engine unhandled rejection\n    at error (/opt/opencti/build/src/config/errors.js:7:10)\n    at UnknownError (/opt/opencti/build/src/config/errors.js:81:47)\n    at process.<anonymous> (/opt/opencti/build/src/boot.js:61:16)\n    at process.emit (node:events:519:28)\n    at process.emit (/opt/opencti/build/node_modules/source-map-support/source-map-support.js:516:21)\n    at emitUnhandledRejection (node:internal/process/promises:250:13)\n    at throwUnhandledRejectionsMode (node:internal/process/promises:385:19)\n    at processPromiseRejections (node:internal/process/promises:470:17)\n    at processTicksAndRejections (node:internal/process/task_queues:96:32)"}],"level":"error","message":"Engine unhandled rejection","source":"backend","timestamp":"2024-11-25T13:35:40.028Z","version":"6.4.0"}
{"category":"APP","errors":[{"attributes":{"genre":"TECHNICAL","http_status":500,"reason":"Error: Cannot set headers after they are sent to the client\n    at ServerResponse.setHeader (node:_http_outgoing:655:11)\n    at ServerResponse.header (/opt/opencti/build/node_modules/express/lib/response.js:794:10)\n    at ServerResponse.send (/opt/opencti/build/node_modules/express/lib/response.js:174:12)\n    at ServerResponse.json (/opt/opencti/build/node_modules/express/lib/response.js:278:15)\n    at ServerResponse.send (/opt/opencti/build/node_modules/express/lib/response.js:162:21)\n    at /opt/opencti/build/src/http/httpPlatform.js:490:21\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"},"message":"Engine unhandled rejection","name":"UNKNOWN_ERROR","stack":"GraphQLError: Engine unhandled rejection\n    at error (/opt/opencti/build/src/config/errors.js:7:10)\n    at UnknownError (/opt/opencti/build/src/config/errors.js:81:47)\n    at process.<anonymous> (/opt/opencti/build/src/boot.js:61:16)\n    at process.emit (node:events:519:28)\n    at process.emit (/opt/opencti/build/node_modules/source-map-support/source-map-support.js:516:21)\n    at emitUnhandledRejection (node:internal/process/promises:250:13)\n    at throwUnhandledRejectionsMode (node:internal/process/promises:385:19)\n    at processPromiseRejections (node:internal/process/promises:470:17)\n    at processTicksAndRejections (node:internal/process/task_queues:96:32)"}],"level":"error","message":"Engine unhandled rejection","source":"backend","timestamp":"2024-11-25T13:43:13.308Z","version":"6.4.0"}
{"category":"APP","errors":[{"attributes":{"genre":"BUSINESS","http_status":400},"message":"Cannot delete an individual corresponding to a user","name":"FUNCTIONAL_ERROR","stack":"GraphQLError: Cannot delete an individual corresponding to a user\n    at error (/opt/opencti/build/src/config/errors.js:7:10)\n    at FunctionalError (/opt/opencti/build/src/config/errors.js:94:50)\n    at internalDeleteElementById (/opt/opencti/build/src/database/middleware.js:3203:13)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at deleteElementById (/opt/opencti/build/src/database/middleware.js:3290:32)\n    at executeDelete (/opt/opencti/build/src/manager/taskManager.js:245:5)\n    at executeProcessing (/opt/opencti/build/src/manager/taskManager.js:498:13)\n    at taskHandler (/opt/opencti/build/src/manager/taskManager.js:602:22)\n    at /opt/opencti/build/src/manager/taskManager.js:635:9\n    at iat.#runHandlerAndScheduleTimeout (/opt/opencti/build/node_modules/set-interval-async/dist/set-interval-async-timer.cjs:36:13)\n    at Timeout._onTimeout (/opt/opencti/build/node_modules/set-interval-async/dist/set-interval-async-timer.cjs:29:13)"}],"level":"error","message":"Cannot delete an individual corresponding to a user","source":"backend","timestamp":"2024-11-25T14:04:07.050Z","version":"6.4.0"}
{"category":"APP","errors":[{"attributes":{"genre":"TECHNICAL","http_status":500,"reason":"Error: Cannot set headers after they are sent to the client\n    at ServerResponse.setHeader (node:_http_outgoing:655:11)\n    at ServerResponse.header (/opt/opencti/build/node_modules/express/lib/response.js:794:10)\n    at ServerResponse.send (/opt/opencti/build/node_modules/express/lib/response.js:174:12)\n    at ServerResponse.json (/opt/opencti/build/node_modules/express/lib/response.js:278:15)\n    at ServerResponse.send (/opt/opencti/build/node_modules/express/lib/response.js:162:21)\n    at /opt/opencti/build/src/http/httpPlatform.js:490:21\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"},"message":"Engine unhandled rejection","name":"UNKNOWN_ERROR","stack":"GraphQLError: Engine unhandled rejection\n    at error (/opt/opencti/build/src/config/errors.js:7:10)\n    at UnknownError (/opt/opencti/build/src/config/errors.js:81:47)\n    at process.<anonymous> (/opt/opencti/build/src/boot.js:61:16)\n    at process.emit (node:events:519:28)\n    at process.emit (/opt/opencti/build/node_modules/source-map-support/source-map-support.js:516:21)\n    at emitUnhandledRejection (node:internal/process/promises:250:13)\n    at throwUnhandledRejectionsMode (node:internal/process/promises:385:19)\n    at processPromiseRejections (node:internal/process/promises:470:17)\n    at processTicksAndRejections (node:internal/process/task_queues:96:32)"}],"level":"error","message":"Engine unhandled rejection","source":"backend","timestamp":"2024-11-25T14:04:09.146Z","version":"6.4.0"}
{"category":"APP","errors":[{"attributes":{"genre":"TECHNICAL","http_status":500,"reason":"Error: Cannot set headers after they are sent to the client\n    at ServerResponse.setHeader (node:_http_outgoing:655:11)\n    at ServerResponse.header (/opt/opencti/build/node_modules/express/lib/response.js:794:10)\n    at ServerResponse.send (/opt/opencti/build/node_modules/express/lib/response.js:174:12)\n    at ServerResponse.json (/opt/opencti/build/node_modules/express/lib/response.js:278:15)\n    at ServerResponse.send (/opt/opencti/build/node_modules/express/lib/response.js:162:21)\n    at /opt/opencti/build/src/http/httpPlatform.js:490:21\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"},"message":"Engine unhandled rejection","name":"UNKNOWN_ERROR","stack":"GraphQLError: Engine unhandled rejection\n    at error (/opt/opencti/build/src/config/errors.js:7:10)\n    at UnknownError (/opt/opencti/build/src/config/errors.js:81:47)\n    at process.<anonymous> (/opt/opencti/build/src/boot.js:61:16)\n    at process.emit (node:events:519:28)\n    at process.emit (/opt/opencti/build/node_modules/source-map-support/source-map-support.js:516:21)\n    at emitUnhandledRejection (node:internal/process/promises:250:13)\n    at throwUnhandledRejectionsMode (node:internal/process/promises:385:19)\n    at processPromiseRejections (node:internal/process/promises:470:17)\n    at processTicksAndRejections (node:internal/process/task_queues:96:32)"}],"level":"error","message":"Engine unhandled rejection","source":"backend","timestamp":"2024-11-25T14:05:20.404Z","version":"6.4.0"}
{"category":"APP","errors":[{"attributes":{"genre":"TECHNICAL","http_status":500,"reason":"Error: Cannot set headers after they are sent to the client\n    at ServerResponse.setHeader (node:_http_outgoing:655:11)\n    at ServerResponse.header (/opt/opencti/build/node_modules/express/lib/response.js:794:10)\n    at ServerResponse.send (/opt/opencti/build/node_modules/express/lib/response.js:174:12)\n    at ServerResponse.json (/opt/opencti/build/node_modules/express/lib/response.js:278:15)\n    at ServerResponse.send (/opt/opencti/build/node_modules/express/lib/response.js:162:21)\n    at /opt/opencti/build/src/http/httpPlatform.js:490:21\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"},"message":"Engine unhandled rejection","name":"UNKNOWN_ERROR","stack":"GraphQLError: Engine unhandled rejection\n    at error (/opt/opencti/build/src/config/errors.js:7:10)\n    at UnknownError (/opt/opencti/build/src/config/errors.js:81:47)\n    at process.<anonymous> (/opt/opencti/build/src/boot.js:61:16)\n    at process.emit (node:events:519:28)\n    at process.emit (/opt/opencti/build/node_modules/source-map-support/source-map-support.js:516:21)\n    at emitUnhandledRejection (node:internal/process/promises:250:13)\n    at throwUnhandledRejectionsMode (node:internal/process/promises:385:19)\n    at processPromiseRejections (node:internal/process/promises:470:17)\n    at processTicksAndRejections (node:internal/process/task_queues:96:32)"}],"level":"error","message":"Engine unhandled rejection","source":"backend","timestamp":"2024-11-25T14:14:31.220Z","version":"6.4.0"}
{"category":"APP","errors":[{"attributes":{"genre":"TECHNICAL","http_status":500,"reason":"Error: Cannot set headers after they are sent to the client\n    at ServerResponse.setHeader (node:_http_outgoing:655:11)\n    at ServerResponse.header (/opt/opencti/build/node_modules/express/lib/response.js:794:10)\n    at ServerResponse.send (/opt/opencti/build/node_modules/express/lib/response.js:174:12)\n    at ServerResponse.json (/opt/opencti/build/node_modules/express/lib/response.js:278:15)\n    at ServerResponse.send (/opt/opencti/build/node_modules/express/lib/response.js:162:21)\n    at /opt/opencti/build/src/http/httpPlatform.js:490:21\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"},"message":"Engine unhandled rejection","name":"UNKNOWN_ERROR","stack":"GraphQLError: Engine unhandled rejection\n    at error (/opt/opencti/build/src/config/errors.js:7:10)\n    at UnknownError (/opt/opencti/build/src/config/errors.js:81:47)\n    at process.<anonymous> (/opt/opencti/build/src/boot.js:61:16)\n    at process.emit (node:events:519:28)\n    at process.emit (/opt/opencti/build/node_modules/source-map-support/source-map-support.js:516:21)\n    at emitUnhandledRejection (node:internal/process/promises:250:13)\n    at throwUnhandledRejectionsMode (node:internal/process/promises:385:19)\n    at processPromiseRejections (node:internal/process/promises:470:17)\n    at processTicksAndRejections (node:internal/process/task_queues:96:32)"}],"level":"error","message":"Engine unhandled rejection","source":"backend","timestamp":"2024-11-25T14:21:58.000Z","version":"6.4.0"}
{"category":"APP","errors":[{"attributes":{"genre":"TECHNICAL","http_status":500,"reason":"Error: Cannot set headers after they are sent to the client\n    at ServerResponse.setHeader (node:_http_outgoing:655:11)\n    at ServerResponse.header (/opt/opencti/build/node_modules/express/lib/response.js:794:10)\n    at ServerResponse.send (/opt/opencti/build/node_modules/express/lib/response.js:174:12)\n    at ServerResponse.json (/opt/opencti/build/node_modules/express/lib/response.js:278:15)\n    at ServerResponse.send (/opt/opencti/build/node_modules/express/lib/response.js:162:21)\n    at /opt/opencti/build/src/http/httpPlatform.js:490:21\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"},"message":"Engine unhandled rejection","name":"UNKNOWN_ERROR","stack":"GraphQLError: Engine unhandled rejection\n    at error (/opt/opencti/build/src/config/errors.js:7:10)\n    at UnknownError (/opt/opencti/build/src/config/errors.js:81:47)\n    at process.<anonymous> (/opt/opencti/build/src/boot.js:61:16)\n    at process.emit (node:events:519:28)\n    at process.emit (/opt/opencti/build/node_modules/source-map-support/source-map-support.js:516:21)\n    at emitUnhandledRejection (node:internal/process/promises:250:13)\n    at throwUnhandledRejectionsMode (node:internal/process/promises:385:19)\n    at processPromiseRejections (node:internal/process/promises:470:17)\n    at processTicksAndRejections (node:internal/process/task_queues:96:32)"}],"level":"error","message":"Engine unhandled rejection","source":"backend","timestamp":"2024-11-25T14:52:49.476Z","version":"6.4.0"}
{"category":"APP","errors":[{"attributes":{"genre":"TECHNICAL","http_status":500,"reason":"Error: Cannot set headers after they are sent to the client\n    at ServerResponse.setHeader (node:_http_outgoing:655:11)\n    at ServerResponse.header (/opt/opencti/build/node_modules/express/lib/response.js:794:10)\n    at ServerResponse.send (/opt/opencti/build/node_modules/express/lib/response.js:174:12)\n    at ServerResponse.json (/opt/opencti/build/node_modules/express/lib/response.js:278:15)\n    at ServerResponse.send (/opt/opencti/build/node_modules/express/lib/response.js:162:21)\n    at /opt/opencti/build/src/http/httpPlatform.js:490:21\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"},"message":"Engine unhandled rejection","name":"UNKNOWN_ERROR","stack":"GraphQLError: Engine unhandled rejection\n    at error (/opt/opencti/build/src/config/errors.js:7:10)\n    at UnknownError (/opt/opencti/build/src/config/errors.js:81:47)\n    at process.<anonymous> (/opt/opencti/build/src/boot.js:61:16)\n    at process.emit (node:events:519:28)\n    at process.emit (/opt/opencti/build/node_modules/source-map-support/source-map-support.js:516:21)\n    at emitUnhandledRejection (node:internal/process/promises:250:13)\n    at throwUnhandledRejectionsMode (node:internal/process/promises:385:19)\n    at processPromiseRejections (node:internal/process/promises:470:17)\n    at processTicksAndRejections (node:internal/process/task_queues:96:32)"}],"level":"error","message":"Engine unhandled rejection","source":"backend","timestamp":"2024-11-25T14:58:17.865Z","version":"6.4.0"}
{"category":"APP","errors":[{"attributes":{"genre":"BUSINESS","http_status":400},"message":"Cannot delete an individual corresponding to a user","name":"FUNCTIONAL_ERROR","stack":"GraphQLError: Cannot delete an individual corresponding to a user\n    at error (/opt/opencti/build/src/config/errors.js:7:10)\n    at FunctionalError (/opt/opencti/build/src/config/errors.js:94:50)\n    at internalDeleteElementById (/opt/opencti/build/src/database/middleware.js:3203:13)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at deleteElementById (/opt/opencti/build/src/database/middleware.js:3290:32)\n    at executeDelete (/opt/opencti/build/src/manager/taskManager.js:245:5)\n    at executeProcessing (/opt/opencti/build/src/manager/taskManager.js:498:13)\n    at taskHandler (/opt/opencti/build/src/manager/taskManager.js:602:22)\n    at /opt/opencti/build/src/manager/taskManager.js:635:9\n    at iat.#runHandlerAndScheduleTimeout (/opt/opencti/build/node_modules/set-interval-async/dist/set-interval-async-timer.cjs:36:13)\n    at Timeout._onTimeout (/opt/opencti/build/node_modules/set-interval-async/dist/set-interval-async-timer.cjs:29:13)"}],"level":"error","message":"Cannot delete an individual corresponding to a user","source":"backend","timestamp":"2024-11-25T14:58:18.065Z","version":"6.4.0"}
{"category":"APP","errors":[{"attributes":{"genre":"BUSINESS","http_status":400},"message":"Only stix-core-relationship can be created through this method.","name":"FUNCTIONAL_ERROR","stack":"GraphQLError: Only stix-core-relationship can be created through this method.\n    at error (/opt/opencti/build/src/config/errors.js:7:10)\n    at FunctionalError (/opt/opencti/build/src/config/errors.js:94:50)\n    at addStixCoreRelationship (/opt/opencti/build/src/domain/stixCoreRelationship.js:98:11)\n    at Object.resolve [as stixCoreRelationshipAdd] (/opt/opencti/build/src/resolvers/stixCoreRelationship.js:108:57)\n    at fieldResolver (/opt/opencti/build/src/graphql/authDirective.js:65:24)\n    at resolveFn (/opt/opencti/build/node_modules/@apollo/server/src/utils/schemaInstrumentation.ts:82:22)\n    at executeField (/opt/opencti/build/node_modules/graphql/execution/execute.js:492:20)\n    at callbackFn (/opt/opencti/build/node_modules/graphql/execution/execute.js:377:22)\n    at promiseReduce (/opt/opencti/build/node_modules/graphql/jsutils/promiseReduce.js:23:9)\n    at executeFieldsSerially (/opt/opencti/build/node_modules/graphql/execution/execute.js:373:29)\n    at executeOperation (/opt/opencti/build/node_modules/graphql/execution/execute.js:347:14)\n    at execute (/opt/opencti/build/node_modules/graphql/execution/execute.js:136:20)\n    at executeIncrementally (/opt/opencti/build/node_modules/@apollo/server/src/incrementalDeliveryPolyfill.ts:114:10)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at f (/opt/opencti/build/node_modules/@apollo/server/src/requestPipeline.ts:543:31)\n    at processGraphQLRequest (/opt/opencti/build/node_modules/@apollo/server/src/requestPipeline.ts:429:26)\n    at internalExecuteOperation (/opt/opencti/build/node_modules/@apollo/server/src/ApolloServer.ts:1331:12)\n    at runHttpQuery (/opt/opencti/build/node_modules/@apollo/server/src/runHttpQuery.ts:232:27)\n    at runPotentiallyBatchedHttpQuery (/opt/opencti/build/node_modules/@apollo/server/src/httpBatching.ts:85:12)\n    at dbe.executeHTTPGraphQLRequest (/opt/opencti/build/node_modules/@apollo/server/src/ApolloServer.ts:1106:14)"}],"inner_relation_creation":0,"level":"error","message":"Only stix-core-relationship can be created through this method.","operation":"Unspecified","query_attributes":[[{"arguments":[[{"is_empty":true,"name":"input","type":"Variable"}]],"name":"stixCoreRelationshipAdd"}]],"size":489,"source":"backend","time":5,"timestamp":"2024-11-25T15:16:38.898Z","type":"WRITE_ERROR","user":{"group_ids":["b3dcc025-7932-438f-9099-a8147dd49109"],"ip":"::ffff:138.4.6.37","organization_ids":[],"socket":"query","user_id":"88ec0c6a-13ce-5e39-b486-354fe4a7084f","user_metadata":{}},"version":"6.4.0"}
{"category":"APP","errors":[{"attributes":{"genre":"TECHNICAL","http_status":500,"reason":"Error: Cannot set headers after they are sent to the client\n    at ServerResponse.setHeader (node:_http_outgoing:655:11)\n    at ServerResponse.header (/opt/opencti/build/node_modules/express/lib/response.js:794:10)\n    at ServerResponse.send (/opt/opencti/build/node_modules/express/lib/response.js:174:12)\n    at ServerResponse.json (/opt/opencti/build/node_modules/express/lib/response.js:278:15)\n    at ServerResponse.send (/opt/opencti/build/node_modules/express/lib/response.js:162:21)\n    at /opt/opencti/build/src/http/httpPlatform.js:490:21\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"},"message":"Engine unhandled rejection","name":"UNKNOWN_ERROR","stack":"GraphQLError: Engine unhandled rejection\n    at error (/opt/opencti/build/src/config/errors.js:7:10)\n    at UnknownError (/opt/opencti/build/src/config/errors.js:81:47)\n    at process.<anonymous> (/opt/opencti/build/src/boot.js:61:16)\n    at process.emit (node:events:519:28)\n    at process.emit (/opt/opencti/build/node_modules/source-map-support/source-map-support.js:516:21)\n    at emitUnhandledRejection (node:internal/process/promises:250:13)\n    at throwUnhandledRejectionsMode (node:internal/process/promises:385:19)\n    at processPromiseRejections (node:internal/process/promises:470:17)\n    at processTicksAndRejections (node:internal/process/task_queues:96:32)"}],"level":"error","message":"Engine unhandled rejection","source":"backend","timestamp":"2024-11-25T15:18:09.812Z","version":"6.4.0"}
{"category":"APP","errors":[{"attributes":{"genre":"TECHNICAL","http_status":500,"reason":"Error: Cannot set headers after they are sent to the client\n    at ServerResponse.setHeader (node:_http_outgoing:655:11)\n    at ServerResponse.header (/opt/opencti/build/node_modules/express/lib/response.js:794:10)\n    at ServerResponse.send (/opt/opencti/build/node_modules/express/lib/response.js:174:12)\n    at ServerResponse.json (/opt/opencti/build/node_modules/express/lib/response.js:278:15)\n    at ServerResponse.send (/opt/opencti/build/node_modules/express/lib/response.js:162:21)\n    at /opt/opencti/build/src/http/httpPlatform.js:490:21\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"},"message":"Engine unhandled rejection","name":"UNKNOWN_ERROR","stack":"GraphQLError: Engine unhandled rejection\n    at error (/opt/opencti/build/src/config/errors.js:7:10)\n    at UnknownError (/opt/opencti/build/src/config/errors.js:81:47)\n    at process.<anonymous> (/opt/opencti/build/src/boot.js:61:16)\n    at process.emit (node:events:519:28)\n    at process.emit (/opt/opencti/build/node_modules/source-map-support/source-map-support.js:516:21)\n    at emitUnhandledRejection (node:internal/process/promises:250:13)\n    at throwUnhandledRejectionsMode (node:internal/process/promises:385:19)\n    at processPromiseRejections (node:internal/process/promises:470:17)\n    at processTicksAndRejections (node:internal/process/task_queues:96:32)"}],"level":"error","message":"Engine unhandled rejection","source":"backend","timestamp":"2024-11-25T15:28:02.313Z","version":"6.4.0"}
{"category":"APP","errors":[{"attributes":{"genre":"BUSINESS","http_status":400},"message":"Cannot delete an individual corresponding to a user","name":"FUNCTIONAL_ERROR","stack":"GraphQLError: Cannot delete an individual corresponding to a user\n    at error (/opt/opencti/build/src/config/errors.js:7:10)\n    at FunctionalError (/opt/opencti/build/src/config/errors.js:94:50)\n    at internalDeleteElementById (/opt/opencti/build/src/database/middleware.js:3203:13)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at deleteElementById (/opt/opencti/build/src/database/middleware.js:3290:32)\n    at executeDelete (/opt/opencti/build/src/manager/taskManager.js:245:5)\n    at executeProcessing (/opt/opencti/build/src/manager/taskManager.js:498:13)\n    at taskHandler (/opt/opencti/build/src/manager/taskManager.js:602:22)\n    at /opt/opencti/build/src/manager/taskManager.js:635:9\n    at iat.#runHandlerAndScheduleTimeout (/opt/opencti/build/node_modules/set-interval-async/dist/set-interval-async-timer.cjs:36:13)\n    at Timeout._onTimeout (/opt/opencti/build/node_modules/set-interval-async/dist/set-interval-async-timer.cjs:29:13)"}],"level":"error","message":"Cannot delete an individual corresponding to a user","source":"backend","timestamp":"2024-11-25T15:28:08.423Z","version":"6.4.0"}
{"category":"APP","errors":[{"attributes":{"genre":"TECHNICAL","http_status":500,"reason":"Error: Cannot set headers after they are sent to the client\n    at ServerResponse.setHeader (node:_http_outgoing:655:11)\n    at ServerResponse.header (/opt/opencti/build/node_modules/express/lib/response.js:794:10)\n    at ServerResponse.send (/opt/opencti/build/node_modules/express/lib/response.js:174:12)\n    at ServerResponse.json (/opt/opencti/build/node_modules/express/lib/response.js:278:15)\n    at ServerResponse.send (/opt/opencti/build/node_modules/express/lib/response.js:162:21)\n    at /opt/opencti/build/src/http/httpPlatform.js:490:21\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"},"message":"Engine unhandled rejection","name":"UNKNOWN_ERROR","stack":"GraphQLError: Engine unhandled rejection\n    at error (/opt/opencti/build/src/config/errors.js:7:10)\n    at UnknownError (/opt/opencti/build/src/config/errors.js:81:47)\n    at process.<anonymous> (/opt/opencti/build/src/boot.js:61:16)\n    at process.emit (node:events:519:28)\n    at process.emit (/opt/opencti/build/node_modules/source-map-support/source-map-support.js:516:21)\n    at emitUnhandledRejection (node:internal/process/promises:250:13)\n    at throwUnhandledRejectionsMode (node:internal/process/promises:385:19)\n    at processPromiseRejections (node:internal/process/promises:470:17)\n    at processTicksAndRejections (node:internal/process/task_queues:96:32)"}],"level":"error","message":"Engine unhandled rejection","source":"backend","timestamp":"2024-11-25T15:28:09.542Z","version":"6.4.0"}
{"category":"APP","errors":[{"attributes":{"genre":"TECHNICAL","http_status":500,"reason":"Error: Cannot set headers after they are sent to the client\n    at ServerResponse.setHeader (node:_http_outgoing:655:11)\n    at ServerResponse.header (/opt/opencti/build/node_modules/express/lib/response.js:794:10)\n    at ServerResponse.send (/opt/opencti/build/node_modules/express/lib/response.js:174:12)\n    at ServerResponse.json (/opt/opencti/build/node_modules/express/lib/response.js:278:15)\n    at ServerResponse.send (/opt/opencti/build/node_modules/express/lib/response.js:162:21)\n    at /opt/opencti/build/src/http/httpPlatform.js:490:21\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"},"message":"Engine unhandled rejection","name":"UNKNOWN_ERROR","stack":"GraphQLError: Engine unhandled rejection\n    at error (/opt/opencti/build/src/config/errors.js:7:10)\n    at UnknownError (/opt/opencti/build/src/config/errors.js:81:47)\n    at process.<anonymous> (/opt/opencti/build/src/boot.js:61:16)\n    at process.emit (node:events:519:28)\n    at process.emit (/opt/opencti/build/node_modules/source-map-support/source-map-support.js:516:21)\n    at emitUnhandledRejection (node:internal/process/promises:250:13)\n    at throwUnhandledRejectionsMode (node:internal/process/promises:385:19)\n    at processPromiseRejections (node:internal/process/promises:470:17)\n    at processTicksAndRejections (node:internal/process/task_queues:96:32)"}],"level":"error","message":"Engine unhandled rejection","source":"backend","timestamp":"2024-11-25T15:36:38.727Z","version":"6.4.0"}
{"category":"APP","errors":[{"attributes":{"genre":"BUSINESS","http_status":400},"message":"Cannot delete an individual corresponding to a user","name":"FUNCTIONAL_ERROR","stack":"GraphQLError: Cannot delete an individual corresponding to a user\n    at error (/opt/opencti/build/src/config/errors.js:7:10)\n    at FunctionalError (/opt/opencti/build/src/config/errors.js:94:50)\n    at internalDeleteElementById (/opt/opencti/build/src/database/middleware.js:3203:13)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at deleteElementById (/opt/opencti/build/src/database/middleware.js:3290:32)\n    at executeDelete (/opt/opencti/build/src/manager/taskManager.js:245:5)\n    at executeProcessing (/opt/opencti/build/src/manager/taskManager.js:498:13)\n    at taskHandler (/opt/opencti/build/src/manager/taskManager.js:602:22)\n    at /opt/opencti/build/src/manager/taskManager.js:635:9\n    at iat.#runHandlerAndScheduleTimeout (/opt/opencti/build/node_modules/set-interval-async/dist/set-interval-async-timer.cjs:36:13)\n    at Timeout._onTimeout (/opt/opencti/build/node_modules/set-interval-async/dist/set-interval-async-timer.cjs:29:13)"}],"level":"error","message":"Cannot delete an individual corresponding to a user","source":"backend","timestamp":"2024-11-25T15:37:27.760Z","version":"6.4.0"}
{"category":"APP","errors":[{"attributes":{"genre":"TECHNICAL","http_status":500,"reason":"Error: Cannot set headers after they are sent to the client\n    at ServerResponse.setHeader (node:_http_outgoing:655:11)\n    at ServerResponse.header (/opt/opencti/build/node_modules/express/lib/response.js:794:10)\n    at ServerResponse.send (/opt/opencti/build/node_modules/express/lib/response.js:174:12)\n    at ServerResponse.json (/opt/opencti/build/node_modules/express/lib/response.js:278:15)\n    at ServerResponse.send (/opt/opencti/build/node_modules/express/lib/response.js:162:21)\n    at /opt/opencti/build/src/http/httpPlatform.js:490:21\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"},"message":"Engine unhandled rejection","name":"UNKNOWN_ERROR","stack":"GraphQLError: Engine unhandled rejection\n    at error (/opt/opencti/build/src/config/errors.js:7:10)\n    at UnknownError (/opt/opencti/build/src/config/errors.js:81:47)\n    at process.<anonymous> (/opt/opencti/build/src/boot.js:61:16)\n    at process.emit (node:events:519:28)\n    at process.emit (/opt/opencti/build/node_modules/source-map-support/source-map-support.js:516:21)\n    at emitUnhandledRejection (node:internal/process/promises:250:13)\n    at throwUnhandledRejectionsMode (node:internal/process/promises:385:19)\n    at processPromiseRejections (node:internal/process/promises:470:17)\n    at processTicksAndRejections (node:internal/process/task_queues:96:32)"}],"level":"error","message":"Engine unhandled rejection","source":"backend","timestamp":"2024-11-25T15:37:28.558Z","version":"6.4.0"}
{"category":"APP","errors":[{"attributes":{"genre":"TECHNICAL","http_status":500,"reason":"Error: Cannot set headers after they are sent to the client\n    at ServerResponse.setHeader (node:_http_outgoing:655:11)\n    at ServerResponse.header (/opt/opencti/build/node_modules/express/lib/response.js:794:10)\n    at ServerResponse.send (/opt/opencti/build/node_modules/express/lib/response.js:174:12)\n    at ServerResponse.json (/opt/opencti/build/node_modules/express/lib/response.js:278:15)\n    at ServerResponse.send (/opt/opencti/build/node_modules/express/lib/response.js:162:21)\n    at /opt/opencti/build/src/http/httpPlatform.js:490:21\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"},"message":"Engine unhandled rejection","name":"UNKNOWN_ERROR","stack":"GraphQLError: Engine unhandled rejection\n    at error (/opt/opencti/build/src/config/errors.js:7:10)\n    at UnknownError (/opt/opencti/build/src/config/errors.js:81:47)\n    at process.<anonymous> (/opt/opencti/build/src/boot.js:61:16)\n    at process.emit (node:events:519:28)\n    at process.emit (/opt/opencti/build/node_modules/source-map-support/source-map-support.js:516:21)\n    at emitUnhandledRejection (node:internal/process/promises:250:13)\n    at throwUnhandledRejectionsMode (node:internal/process/promises:385:19)\n    at processPromiseRejections (node:internal/process/promises:470:17)\n    at processTicksAndRejections (node:internal/process/task_queues:96:32)"}],"level":"error","message":"Engine unhandled rejection","source":"backend","timestamp":"2024-11-25T15:49:21.172Z","version":"6.4.0"}
{"category":"APP","errors":[{"attributes":{"genre":"TECHNICAL","http_status":500,"reason":"Error: Cannot set headers after they are sent to the client\n    at ServerResponse.setHeader (node:_http_outgoing:655:11)\n    at ServerResponse.header (/opt/opencti/build/node_modules/express/lib/response.js:794:10)\n    at ServerResponse.send (/opt/opencti/build/node_modules/express/lib/response.js:174:12)\n    at ServerResponse.json (/opt/opencti/build/node_modules/express/lib/response.js:278:15)\n    at ServerResponse.send (/opt/opencti/build/node_modules/express/lib/response.js:162:21)\n    at /opt/opencti/build/src/http/httpPlatform.js:490:21\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"},"message":"Engine unhandled rejection","name":"UNKNOWN_ERROR","stack":"GraphQLError: Engine unhandled rejection\n    at error (/opt/opencti/build/src/config/errors.js:7:10)\n    at UnknownError (/opt/opencti/build/src/config/errors.js:81:47)\n    at process.<anonymous> (/opt/opencti/build/src/boot.js:61:16)\n    at process.emit (node:events:519:28)\n    at process.emit (/opt/opencti/build/node_modules/source-map-support/source-map-support.js:516:21)\n    at emitUnhandledRejection (node:internal/process/promises:250:13)\n    at throwUnhandledRejectionsMode (node:internal/process/promises:385:19)\n    at processPromiseRejections (node:internal/process/promises:470:17)\n    at processTicksAndRejections (node:internal/process/task_queues:96:32)"}],"level":"error","message":"Engine unhandled rejection","source":"backend","timestamp":"2024-11-25T16:06:21.962Z","version":"6.4.0"}
{"category":"APP","errors":[{"attributes":{"genre":"TECHNICAL","http_status":500,"reason":"Error: Cannot set headers after they are sent to the client\n    at ServerResponse.setHeader (node:_http_outgoing:655:11)\n    at ServerResponse.header (/opt/opencti/build/node_modules/express/lib/response.js:794:10)\n    at ServerResponse.send (/opt/opencti/build/node_modules/express/lib/response.js:174:12)\n    at ServerResponse.json (/opt/opencti/build/node_modules/express/lib/response.js:278:15)\n    at ServerResponse.send (/opt/opencti/build/node_modules/express/lib/response.js:162:21)\n    at /opt/opencti/build/src/http/httpPlatform.js:490:21\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"},"message":"Engine unhandled rejection","name":"UNKNOWN_ERROR","stack":"GraphQLError: Engine unhandled rejection\n    at error (/opt/opencti/build/src/config/errors.js:7:10)\n    at UnknownError (/opt/opencti/build/src/config/errors.js:81:47)\n    at process.<anonymous> (/opt/opencti/build/src/boot.js:61:16)\n    at process.emit (node:events:519:28)\n    at process.emit (/opt/opencti/build/node_modules/source-map-support/source-map-support.js:516:21)\n    at emitUnhandledRejection (node:internal/process/promises:250:13)\n    at throwUnhandledRejectionsMode (node:internal/process/promises:385:19)\n    at processPromiseRejections (node:internal/process/promises:470:17)\n    at processTicksAndRejections (node:internal/process/task_queues:96:32)"}],"level":"error","message":"Engine unhandled rejection","source":"backend","timestamp":"2024-11-25T16:39:07.486Z","version":"6.4.0"}
